server:
  port: 9274

spring:
  application:
    name: bff

launch-server-config:
  projectName: ricardocraft
  mirrors:
    - https://mirror.gravitlauncher.com/5.6.x/
    - https://gravit-launcher-mirror.storage.googleapis.com/
  binaryName: Launcher
  copyBinaries: true
  env: STD
  textureProvider:
    skinURL: http://example.com/skins/%username%.png
    cloakURL: http://example.com/cloaks/%username%.png
    type: REQUEST
  auth:
    std:
      isDefault: true
      core: MEMORY
      displayName: Default
      visible: true
  protectHandler:
    profileWhitelist: { }
    allowUpdates: [ ]
  authLimiter:
    message: Превышен лимит авторизаций
    exclude: [ ]
    rateLimit: 3
    rateLimitMillis: 8000
  proguard:
    modeAfter: MainBuild
    jvmArgs:
      - '-Xmx512M'
    enabled: false
    mappings: true
  launcher:
    compress: true
    stripLineNumbers: true
    deleteTempFiles: true
    certificatePinning: false
    encryptRuntime: false
    customJvmOptions:
      - '-Dfile.encoding=UTF-8'
    memoryLimit: 256
  sign:
    enabled: true
    keyStore: C:\Users\cunningbird\IdeaProjects\ricardocraft-launcher\keystore.jks
    keyStoreType: PKCS12
    keyStorePass: mypass
    keyAlias: ricardocraft
    keyPass: mypass
    metaInfKeyName: SIGNUMO.RSA
    metaInfSfName: SIGNUMO.SF
    signAlgo: SHA256WITHRSA
    checkCertificateExpired: true
  osslSignCodeConfig:
    timestampServer: http://timestamp.sectigo.com
    osslsigncodePath: osslsigncode
    customArgs:
      - '-h'
      - sha256
    checkSignSize: true
    checkCorrectSign: true
    checkCorrectJar: true
  remoteControlConfig:
    list:
      b691bf841037c1b38885bb9f4d88b429:
        permissions: 0
        allowAll: true
        startWithMode: false
        commands: [ ]
    enabled: true
  runtime:
    passwordEncryptKey: aad2ebe2604f9c71c54079c42ffc5b97
    runtimeEncryptKey: 60d7abd7904405be99f10b7641ace3b6
    registerApiKey: ec88066104566ff76136196baf0c0b2f
    clientCheckSecret: fc6c5add66786fb6cf525b2b3ffd7174
    buildNumber: 0
  mirror:
    curseForgeApiKey: 'cead39c6-df96-48aa-9d60-38bf8183beb2'
    deleteTmpDir: false
    workspace:
      fabricMods: []
      quiltMods: []
      forgeMods: []
      lwjgl3version: ''
      lwjglVersionOverride: []
      fabricLoaderVersion: ''
      multiMods: {}
      libraries: []
      build: {}
  localUpdatesProvider:
    cacheFile: .updates-cache
    cacheUpdates: true
  openid:
    tokenUri: 'http:/localhost:7777/oauth2/token'

directories:
  launcherConfigFile: 'config.bin'
  cacheFile: '.updates-cache'
  root: 'C:\Users\cunningbird\IdeaProjects\ricardocraft-launcher\backend\build\app'

netty:
  fileServerEnabled: true
  ipForwarding: false
  disableWebApiInterface: false
  showHiddenFiles: false
  sendProfileUpdatesEvent: true
  launcherURL: http://localhost:9274/Launcher.jar
  downloadURL: http://localhost:9274/%dirname%/
  launcherEXEURL: http://localhost:9274/Launcher.exe
  address: ws://localhost:9274/api
  logLevel: DEBUG
  bindings: { }
  performance:
    usingEpoll: false
    bossThread: 2
    workerThread: 8
    schedulerThread: 2
    maxWebSocketRequestBytes: 1048576
    disableThreadSafeClientObject: false
    executorType: VIRTUAL_THREADS
  security:
    hardwareTokenExpire: 28800
    publicKeyTokenExpire: 28800
    launcherTokenExpire: 28800
  binds:
    - address: 0.0.0.0
      port: 9274