server:
  port: 9274

spring:
  application:
    name: bff

launch-server-config:
  projectName: ricardocraft
  mirrors:
    - https://mirror.gravitlauncher.com/5.6.x/
    - https://gravit-launcher-mirror.storage.googleapis.com/
  binaryName: Launcher
  copyBinaries: true
  env: STD
  auth:
    std:
      isDefault: true
      core: MEMORY
      textureProvider:
        skinURL: http://example.com/skins/%username%.png
        cloakURL: http://example.com/cloaks/%username%.png
        type: REQUEST
      displayName: Default
      visible: true
  protectHandler:
    profileWhitelist: {}
    allowUpdates: []
  components:
    authLimiter:
      message: Превышен лимит авторизаций
      exclude: []
      rateLimit: 3
      rateLimitMillis: 8000
    proguard:
      modeAfter: MainBuild
      dir: proguard
      jvmArgs:
        - '-Xmx512M'
      enabled: true
      mappings: true
  profileProvider:
    profilesDir: profiles
  updatesProvider:
    cacheFile: .updates-cache
    updatesDir: updates
    cacheUpdates: true
  netty:
    fileServerEnabled: true
    ipForwarding: false
    disableWebApiInterface: false
    showHiddenFiles: false
    sendProfileUpdatesEvent: true
    launcherURL: http://localhost:9274/Launcher.jar
    downloadURL: http://localhost:9274/%dirname%/
    launcherEXEURL: http://localhost:9274/Launcher.exe
    address: ws://localhost:9274/api
    bindings: {}
    performance:
      usingEpoll: false
      bossThread: 2
      workerThread: 8
      schedulerThread: 2
      maxWebSocketRequestBytes: 1048576
      disableThreadSafeClientObject: false
      executorType: VIRTUAL_THREADS
    security:
      hardwareTokenExpire: 28800
      publicKeyTokenExpire: 28800
      launcherTokenExpire: 28800
    binds:
      - address: 0.0.0.0
        port: 9274
  launcher:
    compress: true
    stripLineNumbers: true
    deleteTempFiles: true
    certificatePinning: false
    encryptRuntime: false
    customJvmOptions:
      - '-Dfile.encoding=UTF-8'
    memoryLimit: 256
  sign:
    enabled: true
    keyStore: keystore
    keyStoreType: PKCS12
    keyStorePass: mypass
    keyAlias: myname
    keyPass: mypass
    metaInfKeyName: SIGNUMO.RSA
    metaInfSfName: SIGNUMO.SF
    signAlgo: SHA256WITHRSA
    checkCertificateExpired: true
  osslSignCodeConfig:
    timestampServer: http://timestamp.sectigo.com
    osslsigncodePath: osslsigncode
    customArgs:
      - '-h'
      - sha256
    checkSignSize: true
    checkCorrectSign: true
    checkCorrectJar: true
  remoteControlConfig:
    list:
      b691bf841037c1b38885bb9f4d88b429:
        permissions: 0
        allowAll: true
        startWithMode: false
        commands: []
    enabled: true
  mirrorConfig:
    curseforgeApiKey: API_KEY
    deleteTmpDir: false
  runtimeConfig:
    passwordEncryptKey: aad2ebe2604f9c71c54079c42ffc5b97
    runtimeEncryptKey: 60d7abd7904405be99f10b7641ace3b6
    registerApiKey: ec88066104566ff76136196baf0c0b2f
    clientCheckSecret: fc6c5add66786fb6cf525b2b3ffd7174
    buildNumber: 0

